server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: simple-kafka
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
    consumer:
      group-id: ${KAFKA_GROUP_ID:simple-kafka-group}
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false

app:
  kafka:
    topic: ${KAFKA_TOPIC:simple-messages}

logging:
  level:
    ru.bechol.simplekafka: DEBUG
